version: '3.9'
services:
  node:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: cricspin-backend-container
    ports:
      - '8001:8001'
    volumes:
      - ./Backend:/images

  nginx:
    image: nginx:latest
    container_name: cricspin-nginx-container
    ports:
      - '4040:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./Backend:/images:ro # Mount the whole Backend directory to /app/static-files in the Nginx container
    depends_on:
      - node
