# Version of Docker-compose
version: '3.9'
services:
  # Add the node-js service
  node:
  # Location to the node.js dockerfile
    build: 
      context: ./backend
        # Name of the dockerfile
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
       # Host port:Container port
      - '8001:8001'
    volumes:
      # Bind-mounts configuration
      - ./backend:/app
      # Ignoring any changes made in "node_modules" folder
      # - ./app/node_modules