# Version of Docker-compose
version: '3.9'
services:
  # Add the node-js service
  node:
  # Location to the node.js dockerfile
    build: 
      context: ./Backend
        # Name of the dockerfile
      dockerfile: Dockerfile
    container_name: cricspin-backend-container
    ports:
       # Host port:Container port
      - '8001:8001'