name: Node.js CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: self-hosted
        steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses : actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
        - run: |
            cd Frontend
            npm install
            npm run build
            cd ..
            cd Backend
            npm install
            pm2 stop "CricSpin"
            pm2 start npm --name "CricSpin" -- start
            sudo service nginx restart